#!/usr/bin/env python3
"""Write ESSAY.md and RESULTS.md for review on GitHub: the same content as /results.md, with prose split one sentence
per line so pull-request line comments anchor to sentences (Markdown joins consecutive lines, so rendering is unchanged).

  python3 export_md.py            # after prepare_presentation.py; commit on the `review` branch
"""
import json, re
from pathlib import Path
import results_md

SITE = Path(__file__).resolve().parent
LIVE = "https://sim-review-production.up.railway.app"
SENT = re.compile(r'(?<=[.!?…])["”’)]?\s+(?=[A-Z“"(*\d])')


def sentence_lines(md):
    out, fence = [], False
    for line in md.split("\n"):
        if line.startswith("```"): fence = not fence; out.append(line); continue
        s = line.lstrip()
        if fence or not s or s[0] in "|#>-*`" or re.match(r"\d+\. ", s) or len(s) < 140:
            out.append(line); continue
        indent = line[: len(line) - len(s)]
        parts = [p for p in SENT.split(s) if p]
        out.extend(indent + p.strip() for p in parts)
    return "\n".join(out)


summary = json.loads((SITE / "static" / "summary.json").read_text()); pdata = json.loads((SITE / "static" / "presentation-data.json").read_text())
essay = (SITE / "presentation.html").read_text()
head = f"<!-- Generated by export_md.py from presentation.html + static/summary.json + static/presentation-data.json. Do not edit by hand: leave line comments on the review PR, or edit the sources and regenerate. Live site: {LIVE} · this text as served: {LIVE}/results.md -->\n\n"
essay_md = results_md.build(summary, pdata, essay, ["essay"], LIVE)
tables_md = results_md.build(summary, pdata, "", [s for s in results_md.SECTIONS if s != "essay"], LIVE)
(SITE / "ESSAY.md").write_text(head + sentence_lines(essay_md))
(SITE / "RESULTS.md").write_text(head + sentence_lines(tables_md))
for f in ("ESSAY.md", "RESULTS.md"):
    t = (SITE / f).read_text(); print(f"{f}: {len(t):,} chars, {t.count(chr(10)):,} lines")
